version: 2
jobs:
  build-job:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
      - image: selenium/standalone-chrome:latest
    working_directory: ~/rails-5-1-sandbox
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libappindicator1 fonts-liberation
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Bundle Install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format progress
      - store_test_results:
          path: /tmp/test-results

  deploy-job:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
    working_directory: ~/rails-5-1-sandbox
    steps:
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "89:cc:53:52:49:82:dc:4e:83:33:e1:73:20:81:f4:63"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku run rails db:migrate
            heroku restart

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
        requires:
          - build-job
        filters:
          branches:
            only: master
